Deep_Learning_App/urls.py
from django.urls import path, include
from . import views
from TrOCR_Django_App.views import ocr_task_view
app_name = 'Deep_Learning_App'

urlpatterns = [
    path('show_preprocessed_batch/', views.show_preprocessed_batch, name='show_preprocessed_batch'),
    path('configure/', views.configure, name='configure'),
    path('train_model/', views.train_model, name='train_model'),
    path('see_logs/', views.see_logs, name='see_logs'),
    path('make_prediction/', views.make_prediction, name='make_prediction'),
    path('upload_image/', views.upload_image, name='upload_image'),
    
]

TrOCR_Django_App/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', views.ocr_task_view, name='ocr_task_view'),
    path('Deep_Learning_App/', include('Deep_Learning_App.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

Deep_Learning_App/models.py
from django.db import models

# Create your models here.

Deep_Learning_App/forms.py
from django import forms
from Deep_Learning_App.src.config import config

class ConfigForm(forms.Form):
    data_path = forms.CharField(max_length=100, initial=config.data_path, help_text='Dataset directory path')
    deep_learning_model_path = forms.CharField(max_length=100, initial=config.deep_learning_model_path, help_text='DeepLearning Model directory path')
    train_ratio = forms.FloatField(initial=config.train_test_validation_ratios[0], help_text='e.g. 0.15 not 15%')
    validation_ratio = forms.FloatField(initial=config.train_test_validation_ratios[1], help_text='e.g. 0.15 not 15%')
    test_ratio = forms.FloatField(initial=config.train_test_validation_ratios[2], help_text='e.g. 0.15 not 15%')
    split_random_seed = forms.IntegerField(initial=config.split_random_seed)
    batch_size = forms.IntegerField(initial=config.batch_size, help_text='Better be multiples of 2^(.). Typically: 8,16,24,32,...')
    image_height = forms.IntegerField(initial=config.image_height)
    image_width = forms.IntegerField(initial=config.image_width)
    patch_height = forms.IntegerField(initial=config.patch_height)
    patch_width = forms.IntegerField(initial=config.patch_width)
    d_model = forms.IntegerField(initial=config.d_model, help_text='d_model')
    dff = forms.IntegerField(initial=config.dff, help_text='dff')
    num_heads = forms.IntegerField(initial=config.num_heads, help_text='Encoder/ Decoder number of Attention Heads')
    num_layers = forms.IntegerField(initial=config.num_layers, help_text='Encoder/ Decoder number of Number of Attention Layers')
    max_length = forms.IntegerField(initial=config.max_length, help_text='Maximum length to pad')

Deep_Learning_App/views.py
from django.shortcuts import render
from django.http import HttpResponse
import subprocess, os, sys
from Deep_Learning_App.forms import ConfigForm
from Deep_Learning_App.src.config import config
from Deep_Learning_App.data_handler.data_splitter import DataSplitter
from Deep_Learning_App.data_handler.data_loader import CustomDataset
import tensorflow as tf
import random
from PIL import Image
from transformers import AutoTokenizer  # Import the GPT2Tokenizer from the Hugging Face Transformers library


# Create your views here.
def show_preprocessed_batch(request):
        tokenizer = AutoTokenizer.from_pretrained("asafaya/bert-base-arabic")

        data_splitter = DataSplitter(config.data_path, 0.3, config.train_test_validation_ratios[2]) # For testing purpose, we only sample a small set

        train_paths = data_splitter.get_train_paths()
        randomly_sampled_paths = random.sample(train_paths, config.batch_size)
        # training_images_paths = [path+".jpg" for path in randomly_sampled_paths]
        # training_labels_paths = [path+".txt" for path in randomly_sampled_paths] # .replace('\\\\', '\\')
        
        # Since web browsers doesn't allow browsers to access local files, absolute paths won't show up
        # Relative paths works
        
        # context = []
        # context.append({'path': training_images_paths[i], 'label': training_labels_paths[i]})


        # for i in range(len(randomly_sampled_paths)):
        #     index = randomly_sampled_paths[i].find('media')  # Find the index of the subword in the input string
        #     randomly_sampled_paths[i] = randomly_sampled_paths[i][index -1 :]  # Delete everything before the subword
        # print('randomly_sampled_paths', randomly_sampled_paths)
        
        dataset_generator = CustomDataset(randomly_sampled_paths)
        dataset_generator.batch_size = len(randomly_sampled_paths)

        context = []

        # Get a batch of preprocessed image
        for inputs, outputs in dataset_generator:
            outputs = tf.cast(outputs, tf.uint8)
            for i in range(inputs[0].shape[0]):
                tensor_image = tf.cast(inputs[0][i]*255, tf.uint8)
                
                output_text = tokenizer.decode(outputs[i], skip_special_tokens=True)  # Shape: `()`.

                # Convert the TensorFlow tensor to a NumPy array
                numpy_array = tensor_image.numpy()

                # Create a PIL image from the NumPy array
                pil_image = Image.fromarray(numpy_array)
                preprocessed_path = os.path.join(config.data_path, str(i)+'_edited.jpg')
                # print("Saving path:", path)
                pil_image.save(preprocessed_path)

                
                preprocessed_image_index = preprocessed_path.find('media')
                preprocessed_image__index = preprocessed_path.find('dataset')
                preprocessed_path = preprocessed_path[preprocessed_image_index -1 :preprocessed_image__index+len('dataset')+1]

                original_image_index = randomly_sampled_paths[i].find('media')  # Find the index of the subword in the input string
                randomly_sampled_paths[i] = randomly_sampled_paths[i][original_image_index -1 :]  # Delete everything before the subword

                context.append({'original_path': randomly_sampled_paths[i]+".jpg",
                            'processed_path': preprocessed_path+str(i)+"_edited.jpg",
                            'label': output_text})
            break
        
        # print('context', context)
        return render(request, 'show_image_preprocessing.html', {'context': context})


# Create your views here.
def see_logs(request):
    # Start TensorBoard as a subprocess
    process = subprocess.Popen(['tensorboard', '--logdir', config.log_dir])
    # process.wait()

    return render(request, 'see_logs.html', {'config': {'log_dir': config.log_dir}})

        

def configure(request):
    if request.method == 'POST':
        form = ConfigForm(request.POST)
        print("This is a log message")
        if form.is_valid():
            print("This is a log message")
            # Update the config.py variables with the new values
            config.data_path = form.cleaned_data['data_path']
            config.deep_learning_model_path = form.cleaned_data['deep_learning_model_path']
            config.train_test_validation_ratios = [form.cleaned_data['train_ratio'], form.cleaned_data['validation_ratio'], form.cleaned_data['test_ratio']]
            config.split_random_seed = form.cleaned_data['split_random_seed']
            config.batch_size = form.cleaned_data['batch_size']
            config.image_height = form.cleaned_data['image_height']
            config.image_width = form.cleaned_data['image_width']
            config.patch_height = form.cleaned_data['patch_height']
            config.patch_width = form.cleaned_data['patch_width']
            config.d_model = form.cleaned_data['d_model']
            config.dff = form.cleaned_data['dff']
            config.num_heads = form.cleaned_data['num_heads']
            config.num_layers = form.cleaned_data['num_layers']
            config.max_length = form.cleaned_data['max_length']
            # Save the changes if necessary

            # Redirect to a success page or render a response
            # (e.g., show updated configuration or a confirmation message)
            return render(request, 'success_form.html')
        else:
            # Form is invalid, display error messages
            print(form.errors)
    else:
        form = ConfigForm()

    return render(request, 'config_form.html', {'form': form})


def train_model(request):
    venv_python = sys.executable
    subprocess_cmd = [venv_python, 'Deep_Learning_App/src/train.py']
    working_directory = os.getcwd()

    # change_dir_cmd = ['cd', working_directory]
    # subprocess.Popen(change_dir_cmd, shell=True).wait()  # Use shell=True for the cd command

    process = subprocess.Popen(subprocess_cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, universal_newlines=True, cwd=working_directory, shell=True)

    # Start TensorBoard as a subprocess
    command = f'tensorboard --logdir={config.log_dir}'
    process = subprocess.Popen(command, shell=True)


    # stdout, stderr = process.communicate()
    # return render(request, 'training.html', {'stdout': stdout, 'stderr': stderr})
    return render(request, 'training.html')

def upload_image(request):
    if request.method == 'POST' and request.FILES['image']:
        uploaded_image = request.FILES['image']
        uploaded_image = os.path.join(os.getcwd(), 'media', 'dataset', str(uploaded_image))
        return render(request, 'upload_successful.html', {'filename': uploaded_image})
    return render(request, 'upload_image.html')

def make_prediction(request):
    image_path = request.GET.get('image_path', '')
    # return HttpResponse(f'Image path received: {image_path}')
    venv_python = sys.executable
    script_path = os.path.join(os.getcwd(), 'Deep_Learning_App', 'src', 'predict.py')
    subprocess_cmd = [venv_python, script_path]
    additional_args = ['--image_path', image_path]
    subprocess_cmd.extend(additional_args)
    working_directory = os.getcwd()

    print(subprocess_cmd)
    process = subprocess.Popen(subprocess_cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, universal_newlines=True, cwd=working_directory, shell=True, text=True)
    from subprocess import check_output
    out = check_output(subprocess_cmd)

    return_code = process.wait()
    (stdoutdata, stderrdata) = process.communicate()
    # exit_code = process.returncode


    # output, _ = process.communicate()

    # output = process.stdout.read()
    # print(f"Return code: {return_code}")
    print(f"Output: {stdoutdata}, {out}")

    # print(process)
    # output, _ = process.communicate()

    # # Get the stdout and stderr from the result
    # stdout_output = output.stdout
    # stderr_output = output.stderr

    # context = {
    #     'stdout_output': stdout_output,
    #     'stderr_output': stderr_output,
    # }
    
    
    # # # Start TensorBoard as a subprocess
    # # command = f'tensorboard --logdir={config.log_dir}'
    # # process = subprocess.Popen(command, shell=True)


    # # # stdout, stderr = process.communicate()
    # # # return render(request, 'training.html', {'stdout': stdout, 'stderr': stderr})
    # # return render(request, 'training.html')

    # # You can use the context in your template or return an HttpResponse
    return HttpResponse(f'Stdout Output: {stdoutdata}<br>')

Deep_Learning_App/templates/config_form.html
<!-- config_form.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Configuration Form</title>
    <style>
        /* Add your custom CSS styles here */
        body {
            font-family: Arial, sans-serif;
            background-color: #f2f2f2;
            margin: 0;
            padding: 0;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }

        .container {
            background-color: #ffffff;
            border-radius: 8px;
            padding: 20px;
            box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
            overflow-y: auto; /* Enable vertical scrolling */
            max-height: 80vh; /* Set a maximum height for the container */
        }

        h1 {
            text-align: center;
            font-size: 24px; /* Increase font size for emphasis */
            margin-bottom: 20px; /* Add some space below the title */
        }

        /* Style for form elements */
        form {
            width: 300px;
            margin: 0 auto;
        }

        label {
            font-weight: bold;
            display: block;
            margin-bottom: 8px;
        }

        input[type="text"],
        select,
        button {
            width: 100%;
            padding: 10px;
            margin-bottom: 15px;
            border: 1px solid #ccc;
            border-radius: 4px;
            box-sizing: border-box;
        }

        button {
            background-color: #007BFF;
            color: white;
            border: none;
            cursor: pointer;
        }

        button:hover {
            background-color: #0056b3;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="scrollable-content"> <!-- Added a wrapping div for scrolling -->
            <h1>Configuration Form</h1>        
            <form method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Save Configuration</button>
            </form>
        </div>
    </div>
</body>
</html>

Deep_Learning_App/templates/see_logs.html
<!DOCTYPE html>
<html>
<head>
    <title>See Logs</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f2f2f2;
            margin: 0;
            padding: 0;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }

        .container {
            max-width: 800px;
            padding: 20px;
            background-color: #fff;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            border-radius: 10px;
            text-align: center;
        }

        h1 {
            color: #333;
        }

        .message {
            margin: 20px 0;
        }

        .button {
            display: inline-block;
            padding: 10px 20px;
            background-color: #007BFF;
            color: #fff;
            font-size: 16px;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            transition: background-color 0.3s ease;
            
        }

        .button:last-child {
            margin-right: 0; /* Remove margin from the last button */
        }

        .button:hover {
            background-color: #0056b3;
        }
        .back-link {
            text-align: center;
            margin-top: 10px;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Tensorboard is running</h1>
        <div class="message">
            TensorBoard has started at:
            <br>
            <code>{{ log_dir }}</code>
        </div>
        <a class="button" href="http://localhost:6006/" target="_blank">Open TensorBoard</a>
        <div class="back-link">
            <span class="button">
                <a href="{% url 'ocr_task_view' %}" class="button-link">Back to Main Menu</a>
            </span>
        </div>
    </div>
</body>
</html>

Deep_Learning_App/templates/show_image_preprocessing.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Show Images</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            text-align: center;
            background-color: #f7f7f7;
        }

        h1 {
            background-color: #333;
            color: #fff;
            padding: 20px;
            margin: 0;
        }

        .image-container {
            display: flex;
            justify-content: center;
            flex-wrap: wrap;
            margin-top: 20px;
        }

        .image-card {
            background-color: #fff;
            border: 1px solid #e0e0e0;
            border-radius: 5px;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
            margin: 10px;
            padding: 15px;
            width: 300px;
        }

        .image-card img {
            max-width: 100%;
            height: auto;
            border-radius: 5px;
            margin-top: 10px;
        }

        .image-card p {
            font-weight: bold;
            margin-top: 10px;
        }
        .button {
            text-align: center;
            margin-top: 20px;
        }

        .button-link {
            display: inline-block;
            padding: 10px 20px; /* Adjust padding to your liking */
            background-color: #007bff; /* Change to your desired button color */
            color: #fff; /* Text color */
            text-decoration: none;
            border-radius: 4px;
            border: none;
            cursor: pointer;
            transition: background-color 0.3s ease;
        }
        .button-link:hover {
            background-color: #0056b3; /* Change to the hover color you prefer */
        }
    </style>
</head>
<body>
    <h1>Display Batch Of Images</h1>
    <div class="image-container">
        {% for item in context %}
            <div class="image-card">
                <img src="{{ item.original_path }}" alt="Original Image">
                <img src="{{ item.processed_path }}" alt="Preprocessed Image">
                <p>{{ item.label }}</p>                

            </div>
        {% endfor %}
    
    </div>

    <div class="back-link">
        <span class="button">
            <a href="{% url 'ocr_task_view' %}" class="button-link">Back to Main Menu</a>
        </span>
    </div>
    
</body>
</html>

Deep_Learning_App/templates/success_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Configuration Updated Successfully</title>
    <style>
        /* Add your custom CSS styles here */
        body {
            font-family: Arial, sans-serif;
            background-color: #f2f2f2;
            margin: 0;
            padding: 0;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }

        .container {
            background-color: #ffffff;
            border-radius: 8px;
            padding: 20px;
            box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
        }

        h1 {
            text-align: center;
        }

        p {
            text-align: center;
        }

        /* Optional: Style for displaying updated configuration values */
        .updated-config {
            margin-top: 20px;
            background-color: #f5f5f5;
            padding: 10px;
            border-radius: 4px;
            border: 1px solid #ccc;
        }

        /* Style for the "Back to main menu" link */
        .back-link {
            text-align: center;
            margin-top: 20px;
        }
        /* Style for the "Back to Main Menu" button */
        .button {
            text-align: center;
            margin-top: 20px;
        }

        .button-link {
            display: inline-block;
            padding: 10px 20px; /* Adjust padding to your liking */
            background-color: #007bff; /* Change to your desired button color */
            color: #fff; /* Text color */
            text-decoration: none;
            border-radius: 4px;
            border: none;
            cursor: pointer;
            transition: background-color 0.3s ease;
        }

        .button-link:hover {
            background-color: #0056b3; /* Change to the hover color you prefer */
        }

    </style>
</head>
<body>
    <div class="container">
        <h1>Configuration Updated</h1>
        <p>Your configuration has been updated successfully.</p>
        <!-- Display the updated configuration values here if needed -->
        <div class="updated-config">
            <!-- Insert updated configuration values here -->
        </div>
        <!-- "Back to main menu" link -->
        <div class="back-link">
            <span class="button">
                <a href="{% url 'ocr_task_view' %}" class="button-link">Back to Main Menu</a>
            </span>
        </div>
    </div>
</body>
</html>

Deep_Learning_App/templates/training.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Training is running...</title>
    <style>
        /* Add your custom CSS styles here */
        body {
            font-family: Arial, sans-serif;
            background-color: #f5f5f5;
            margin: 0;
            padding: 0;
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            height: 100vh;
        }

        .container {
            background-color: #fff;
            border-radius: 8px;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);
            padding: 20px;
            text-align: center;
        }

        h1 {
            color: #007bff;
        }

        p {
            margin-top: 20px;
        }

        a {
            display: inline-block;
            padding: 10px 20px;
            background-color: #007bff;
            color: #fff;
            text-decoration: none;
            border-radius: 4px;
            transition: background-color 0.3s ease;
        }

        a:hover {
            background-color: #0056b3;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Training is starting, Run TensorBoard?</h1>
        <p>Click the link below to open TensorBoard at <a href="http://localhost:6006/" target="_blank">localhost:6006</a>:</p>
        
    </div>
</body>
</html>

Deep_Learning_App/templates/upload_image.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Image Upload</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f2f2f2;
        }

        .container {
            max-width: 400px;
            margin: 0 auto;
            padding: 20px;
            background-color: #fff;
            border-radius: 5px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            text-align: center;
        }

        h1 {
            margin-top: 0;
        }

        .file-input {
            margin: 20px 0;
            position: relative;
        }

        input[type="file"] {
            display: none;
        }

        label {
            padding: 10px 15px;
            background-color: #007BFF;
            color: #fff;
            border-radius: 3px;
            cursor: pointer;
        }

        button {
            background-color: #007BFF;
            color: #fff;
            padding: 10px 15px;
            border: none;
            border-radius: 3px;
            cursor: pointer;
            transition: background-color 0.3s ease;
        }

        button:hover {
            background-color: #0056b3;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Upload an Image</h1>
        <form method="POST" action="/Deep_Learning_App/upload_image/" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="file-input">
                <input type="file" name="image" id="image" accept=".jpg">
                <label for="image">Choose a .jpg image</label>
            </div>
            <button type="submit">Upload</button>
        </form>
    </div>
</body>
</html>

Deep_Learning_App/templates/upload_successful.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Upload Successful</title>
    <style>
        body {
            font-family: 'Arial', sans-serif;
            background-color: #f2f2f2;
            margin: 0;
            padding: 0;
        }

        .container {
            background-color: #fff;
            border-radius: 5px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            text-align: center;
            margin: 10% auto;
            padding: 20px;
            max-width: 400px;
        }

        h1 {
            margin: 0 0 20px;
            color: #007BFF;
        }

        p {
            font-size: 18px;
            margin: 0 0 20px;
        }

        strong {
            color: #0056b3;
        }

        a {
            display: inline-block;
            padding: 10px 15px;
            background-color: #007BFF;
            color: #fff;
            text-decoration: none;
            border-radius: 3px;
            transition: background-color 0.3s ease;
        }

        a:hover {
            background-color: #0056b3;
        }
        .fancy-button {
            display: inline-block;
            padding: 10px 20px;
            background-color: #007BFF; /* Button background color */
            color: white; /* Button text color */
            text-decoration: none; /* Remove underlines from the link */
            border-radius: 4px; /* Rounded corners */
            transition: background-color 0.3s ease; /* Smooth hover effect */
            margin-right: 10px; /* Right margin between buttons */
        }

        .fancy-button:hover {
            background-color: #0056b3; /* Button background color on hover */
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Upload Successful</h1>
        <p>The image <strong>{{ filename }}</strong> has been successfully uploaded.</p>
        <a href="{% url 'Deep_Learning_App:make_prediction' %}?image_path={{filename}}" class="fancy-button">Predict</a>      

    </div>
</body>
</html>